/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package GitExample

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test


class AppTest {

    @Test
    fun testAppHasAGreeting() {
        assertThat(3 + 7).isEqualTo(10)
    }
}
