/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package GitExample

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test


class AppTest {

    @Test
    fun testAppHasAGreeting() {
        assertThat(2 + 3).isEqualTo(7)
    }
}
